name        : libcue
version     : 1.4.0
release     : 3
source      :
    - http://internode.dl.sourceforge.net/project/libcue/libcue/1.4.0/libcue-1.4.0.tar.bz2 : 8b7276ec2a2b3918cbc59a3cc03c68dc0775965cc20e4b88757b852ff369729e
homepage    : http://sourceforge.net/projects/libcue/
license     :
    - GPLv2
summary     : Cue sheet parser library
description : |
    libcue is intended for parsing a so-called cue sheet from a char string or a file pointer.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
