name       : libcue
version    : 2.2.1
release    : 5
source     :
    - https://github.com/lipnitsk/libcue/archive/v2.2.1.tar.gz : f27bc3ebb2e892cd9d32a7bee6d84576a60f955f29f748b9b487b173712f1200
homepage   : http://sourceforge.net/projects/libcue/
license    : GPL-2.0
component  : multimedia.library
summary    : Cue sheet parser library
description: |
    libcue is intended for parsing a so-called cue sheet from a char string or a file pointer.
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
