name       : libcue
version    : 2.1.0
release    : 4
source     :
    - https://github.com/lipnitsk/libcue/archive/v2.1.0.tar.gz : 288ddd01e5f9e8f901d0c205d31507e4bdffd2540fa86073f2fe82de066d2abb
homepage   : http://sourceforge.net/projects/libcue/
license    : GPL-2.0
component  : multimedia.library
summary    : Cue sheet parser library
description: |
    libcue is intended for parsing a so-called cue sheet from a char string or a file pointer.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
